name: deploy

on:
  push:
    branches:
    - main
  pull_request:
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install prerequisites
      run: ./themes/tale-hugo/scripts/install-prerequisites.sh

    - name: Build
      run: ./themes/tale-hugo/scripts/build.sh

    - name: Configure custom domain
      run: echo "www.lind.sh" > ./public/CNAME

    - name: Deploy
      run: ./themes/tale-hugo/scripts/deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Purge cache
      run: |
        curl \
          -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
          -H "Authorization: Bearer $CLOUDFLARE_CACHE_PURGE_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_CACHE_PURGE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_PURGE_TOKEN }}
